//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi_LuaChon
    {
        public int MaCauHoi { get; set; }
        public int MaLuaChon { get; set; }
        public bool CauTraLoi { get; set; }
    
        public virtual CauHois CauHois { get; set; }
        public virtual LuaChon LuaChon { get; set; }
    }
}
