//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.DeThi_CauHoi = new HashSet<DeThi_CauHoi>();
            this.HocSinh_DeThi = new HashSet<HocSinh_DeThi>();
        }
    
        public int MaDeThi { get; set; }
        public Nullable<int> MaMonThi { get; set; }
        public string TenMonThi { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<int> SoCauHoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi_CauHoi> DeThi_CauHoi { get; set; }
        public virtual MonThi MonThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocSinh_DeThi> HocSinh_DeThi { get; set; }
    }
}
