//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh_KhoaHoc
    {
        public int MaHocSinh { get; set; }
        public int MaKhoaHoc { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
